import os

# RESULT DIRECTORIES
DATA_DIR = "data"
FIGURES_DIR = "figures"
REPORTS_DIR = "reports"


# REAL NBU SETTINGS
NBU_CURRENCIES = ["USD", "EUR", "RUB"]
NBU_START_DATE = "2023-01-01"
NBU_END_DATE = "2025-12-31"
NBU_TRAIN_RATIO = 0.7
NBU_CSV_PATH = os.path.join(DATA_DIR, "multi_currency_data.csv")

DATASET10_PATH = os.path.join(DATA_DIR, "Data_Set_10.xls")

# TS DECOMPOSITION / SYNTH GENERATION
TS_DECOMP_MODEL = "additive"
TS_DECOMP_PERIOD_SYN = 30
TS_DECOMP_PERIOD_NBU = 30
TS_DECOMP_PERIOD_DS10 = 12
TS_SYNTHETIC_YEARS = 3
TS_NOISE_SCALE = 0.5

# DATASET_10 SETTINGS

LINEAR_TRAIN_RATIO_DS10 = 0.5

DATASET10_REGION_COL = "Region"
DATASET10_DATE_COL = "Order Date"
DATASET10_VALUE_COL = "Sales"
DATASET10_TRAIN_RATIO = 0.7

# RANDOM / CLUSTERING
RANDOM_STATE = 42
N_CLUSTERS = 3

# ANOMALY DETECTION / ENTROPY
ANOMALY_WINDOW = 10
ANOMALY_BASE_K = 3.0
ANOMALY_ALPHA = 1.5
ANOMALY_BINS = 30

# ALPHA-BETA(-GAMMA) FILTERS
AB_ALPHA = 0.85
AB_BETA = 0.005
ABG_ALPHA = 0.85
ABG_BETA = 0.1
ABG_GAMMA = 0.01
DT = 1.0

# MOVING AVERAGE / ARIMA / EXTRAPOLATION
DEFAULT_MA_WINDOW = 7

MA_WINDOW_CANDIDATES = [3, 5, 7, 10, 14, 21, 30]

ARIMA_P_RANGE = [0, 1, 2]
ARIMA_D_RANGE = [0, 1, 2]
ARIMA_Q_RANGE = [0, 1, 2]

FORECAST_HORIZONS = (0.5, 1.0, 1.5, 2.0)


# EXPONENTIAL SMOOTHING
ES_TRAIN_VAL_RATIO = 0.2
